package/rng-tools: cherry-pick fix for jitterentropy build failure
Since commit a8807d updated jitterentropy-library to version 3.4.1.

jitterentropy-library requires setting the macro JENT_CONF_ENABLE_INTERNAL_TIMER
to define jent_notime_ctx. If not set, the build fails with the following error:

rngd_jitter.c: In function ‘rngd_notime_stop’:
rngd_jitter.c:97:32: error: invalid use of undefined type ‘struct jent_notime_ctx’
   97 |         pthread_join(thread_ctx->notime_thread_id, NULL);

Reference:
https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg160531.html

There has not been a release with the fix yet.

Cherry-pick the upstream commit as a patch:

https://github.com/nhorman/rng-tools/commit/57be6d4c90e78ea9ad036a3a6e9b09822ed4d219

Signed-off-by: Christian Stewart <christian@paral.in>

---

v1 -> v2:

 - cherry-picked the upstream commit instead of creating our own

Signed-off-by: Christian Stewart <christian@paral.in>