boot/uboot: add host-python-pylibfdt dependency if needed
If BR2_TARGET_UBOOT_NEEDS_PYLIBFDT is set, add a dependency on
host-python-pylibfdt.

Fixes a build failure with uboot 2023.07:

$ make uboot
error: pylibfdt does not seem to be available with python3

Signed-off-by: Christian Stewart <christian@aperture.us>