package/rng-tools: fix build failure: undefined jent_notime_ctx
Since commit a8807d updated jitterentropy-library to version 3.4.1:

The update requires setting the macro JENT_CONF_ENABLE_INTERNAL_TIMER, otherwise
the build can fail with the following type of error:

jitterentropy-library requires setting the macro JENT_CONF_ENABLE_INTERNAL_TIMER
to define jent_notime_ctx. If not set, the build fails with the following error:

rngd_jitter.c: In function ‘rngd_notime_stop’:
rngd_jitter.c:97:32: error: invalid use of undefined type ‘struct jent_notime_ctx’
   97 |         pthread_join(thread_ctx->notime_thread_id, NULL);

Reference:
https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg160531.html

Signed-off-by: Christian Stewart <christian@paral.in>